import "./globals.css";
import { Inter } from "next/font/google";
import { AppProvider } from "@app/components/app-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          className="my-app-bar border-gray-200"
         
        >
          <div className=" bg-amber-500 flex flex-wrap items-center justify-between p-4  ">
            <a href="/" class="flex items-center no-underline">
              <span className="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">
                QunnTr.
              </span>
            </a>
            
            <div
              className="hidden w-full md:block md:w-auto"
              id="navbar-solid-bg"
            >
              <ul className="list-none flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-transparent ">
                <li>
                  <a
                    href="/"
                    className=""
                  >
                    Home
                  </a>
                </li>
                <li>
                  <a
                    href="/students"
                    className=""
                  >
                    Students
                  </a>
                </li>
            
              </ul>
            </div>
          </div>
        </nav>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
